import type { InlineCommentData } from '@diff-viewer'

const mockComment: InlineCommentData = {
  id: 123,
  body: 'This is a great improvement! The code is much cleaner now. Consider adding a comment here to explain the logic.',
  user: {
    login: 'alice',
    avatar_url: 'https://avatars.githubusercontent.com/u/123?v=4',
    html_url: 'https://github.com/alice',
    id: 123,
    node_id: 'MDQ6VXNlcjEyMw==',
    gravatar_id: '',
    url: 'https://api.github.com/users/alice',
    type: 'User',
    site_admin: false,
    followers_url: 'https://api.github.com/users/alice/followers',
    following_url: 'https://api.github.com/users/alice/following{/other_user}',
    gists_url: 'https://api.github.com/users/alice/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/alice/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/alice/subscriptions',
    organizations_url: 'https://api.github.com/users/alice/orgs',
    repos_url: 'https://api.github.com/users/alice/repos',
    events_url: 'https://api.github.com/users/alice/events{/privacy}',
    received_events_url: 'https://api.github.com/users/alice/received_events',
  },
  created_at: '2024-01-15T10:30:00Z',
  updated_at: '2024-01-15T10:30:00Z',
  html_url: 'https://github.com/owner/repo/pull/123#discussion_r123',
  url: 'https://api.github.com/repos/owner/repo/pulls/comments/123',
  pull_request_review_id: null,
  node_id: 'MDEyOkNvbW1lbnQxMjM=',
  diff_hunk: '@@ -1,3 +1,3 @@\n-old line\n+new line',
  path: 'src/file.ts',
  position: 1,
  original_position: 1,
  commit_id: 'abc123',
  original_commit_id: 'abc123',
  in_reply_to_id: null,
  pull_request_url: 'https://api.github.com/repos/owner/repo/pulls/123',
  author_association: 'CONTRIBUTOR',
  _links: {
    self: { href: 'https://api.github.com/repos/owner/repo/pulls/comments/123' },
    html: { href: 'https://github.com/owner/repo/pull/123#discussion_r123' },
    pull_request: { href: 'https://api.github.com/repos/owner/repo/pulls/123' },
  },
  reactions: {
    url: 'https://api.github.com/repos/owner/repo/pulls/comments/123/reactions',
    total_count: 4,
    '+1': 2,
    '-1': 0,
    laugh: 1,
    hooray: 0,
    confused: 0,
    heart: 1,
    rocket: 0,
    eyes: 0,
  },
  start_line: null,
  original_start_line: null,
  start_side: null,
  line: 14,
  original_line: 14,
  side: 'RIGHT',
  subject_type: 'line',
}

export default mockComment
