import type { GitHubUser } from '../api/models'

export const USER_DATA: GitHubUser = {
  login: 'edsilfer',
  id: 12755321,
  node_id: 'MDQ6VXNlcjEyNzU1MzIx',
  avatar_url: 'https://avatars.githubusercontent.com/u/12755321?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/edsilfer',
  html_url: 'https://github.com/edsilfer',
  followers_url: 'https://api.github.com/users/edsilfer/followers',
  following_url: 'https://api.github.com/users/edsilfer/following{/other_user}',
  gists_url: 'https://api.github.com/users/edsilfer/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/edsilfer/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/edsilfer/subscriptions',
  organizations_url: 'https://api.github.com/users/edsilfer/orgs',
  repos_url: 'https://api.github.com/users/edsilfer/repos',
  events_url: 'https://api.github.com/users/edsilfer/events{/privacy}',
  received_events_url: 'https://api.github.com/users/edsilfer/received_events',
  type: 'User',
  user_view_type: 'public',
  site_admin: false,
  name: 'Edgar Fernandes',
  company: null,
  blog: 'https://br.linkedin.com/in/edsilfer',
  location: 'Amsterdam - Netherlands',
  email: null,
  notification_email: null,
  hireable: true,
  bio: 'Software Engineer',
  twitter_username: null,
  public_repos: 14,
  public_gists: 0,
  followers: 57,
  following: 23,
  created_at: '2015-06-05T00:47:26Z',
  updated_at: '2025-07-08T09:30:03Z',
}
